spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 547717253
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
pagehelper:
  helper-dialect: mysql
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:com/example/demo/mapper/*.xml
logging:
  level:
    com: debug